// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace firstApplication.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20211119001426_MigrationRecestas")]
    partial class MigrationRecestas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("firstApplication.Models.Recipes", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RecAutor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecIngredientes")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RecNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RecId");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
